"""add_composite_indexes_to_click_events

Revision ID: 04b40ee2ca30
Revises: 06a90fb4b7e6
Create Date: 2026-05-02 19:23:48.687458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b40ee2ca30'
down_revision: Union[str, Sequence[str], None] = '06a90fb4b7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_index('ix_click_events_link_country', 'click_events', ['link_id', 'country'], unique=False)
    op.create_index('ix_click_events_link_referer', 'click_events', ['link_id', 'referer'], unique=False)
    op.create_index('ix_click_events_link_clicked_at', 'click_events', ['link_id', 'clicked_at'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_click_events_link_clicked_at', table_name='click_events')
    op.drop_index('ix_click_events_link_referer', table_name='click_events')
    op.drop_index('ix_click_events_link_country', table_name='click_events')
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
