"""add_is_public_stats_to_links

Revision ID: 17037ce2c17d
Revises: 5a3c67bc7b07
Create Date: 2026-05-05 21:45:30.796582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17037ce2c17d'
down_revision: Union[str, Sequence[str], None] = '5a3c67bc7b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('is_public_stats', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'is_public_stats')
    # ### end Alembic commands ###
