"""add_is_unique_to_click_events

Revision ID: 3cee09c9d8b1
Revises: 04b40ee2ca30
Create Date: 2026-05-04 14:57:12.073725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cee09c9d8b1'
down_revision: Union[str, Sequence[str], None] = '04b40ee2ca30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('click_events', sa.Column('is_unique', sa.Boolean(), nullable=True))

    # Update existing rows to have is_unique=True
    op.execute("UPDATE click_events SET is_unique = TRUE")

    # Now set it to NOT NULL
    op.alter_column('click_events', 'is_unique', nullable=False)

    op.create_index(op.f('ix_click_events_is_unique'), 'click_events', ['is_unique'], unique=False)
    op.create_index('ix_link_user_created', 'links', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_link_user_created', table_name='links')
    op.drop_index(op.f('ix_click_events_is_unique'), table_name='click_events')
    op.drop_column('click_events', 'is_unique')
    # ### end Alembic commands ###
