"""remove_is_unique_field

Revision ID: 5a3c67bc7b07
Revises: 2bfd160ae6e1
Create Date: 2026-05-05 21:25:02.371724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3c67bc7b07'
down_revision: Union[str, Sequence[str], None] = '2bfd160ae6e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_click_events_is_unique'), table_name='click_events')
    op.drop_column('click_events', 'is_unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click_events', sa.Column('is_unique', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_click_events_is_unique'), 'click_events', ['is_unique'], unique=False)
    # ### end Alembic commands ###
