"""init

Revision ID: a960312fe406
Revises:
Create Date: 2026-03-17 19:46:46.586003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a960312fe406'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('links', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('links', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_links_user_id'), 'links', ['user_id'], unique=False)
    op.drop_constraint(op.f('links_user_id_fkey'), 'links', type_='foreignkey')
    op.create_foreign_key(None, 'links', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('links', 'expire_at')
    op.drop_column('links', 'custom_alias')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'is_active')
    op.add_column('links', sa.Column('custom_alias', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('links', sa.Column('expire_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.create_foreign_key(op.f('links_user_id_fkey'), 'links', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_links_user_id'), table_name='links')
    op.alter_column('links', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('links', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('links', 'expires_at')
    # ### end Alembic commands ###
